version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/wp-content/themes/engage-2-x"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/wp-content/themes/engage-2-x"
    schedule:
      interval: "weekly"
