<?php
	require_once(THEME_SHORTCODES_PATH.'dropcaps.php');
	require_once(THEME_SHORTCODES_PATH.'tab.php');
	require_once(THEME_SHORTCODES_PATH.'tooltip.php');
	require_once(THEME_SHORTCODES_PATH.'accordion.php');
	require_once(THEME_SHORTCODES_PATH.'buttons.php');
	require_once(THEME_SHORTCODES_PATH.'marker.php');
	require_once(THEME_SHORTCODES_PATH.'lists.php');
	require_once(THEME_SHORTCODES_PATH.'columns.php');
	require_once(THEME_SHORTCODES_PATH.'miscellaneous.php');
	require_once(THEME_SHORTCODES_PATH.'icon.php');
	require_once(THEME_SHORTCODES_PATH.'qoutes.php');
	require_once(THEME_SHORTCODES_PATH.'social.php');
	require_once(THEME_SHORTCODES_PATH.'clear.php');
	require_once(THEME_SHORTCODES_PATH.'spacers.php');
	require_once(THEME_SHORTCODES_PATH.'gallery-box.php');
?>