<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit58f069f58cffa522470ca297c1368bdf
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('NF_FU_VENDOR\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \NF_FU_VENDOR\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit58f069f58cffa522470ca297c1368bdf', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \NF_FU_VENDOR\Composer\Autoload\ClassLoader(\dirname(\dirname(__FILE__)));
        spl_autoload_unregister(array('ComposerAutoloaderInit58f069f58cffa522470ca297c1368bdf', 'loadClassLoader'));

        $useStaticLoader = PHP_VERSION_ID >= 50600 && !defined('HHVM_VERSION') && (!function_exists('zend_loader_file_encoded') || !zend_loader_file_encoded());
        if ($useStaticLoader) {
            require __DIR__ . '/autoload_static.php';

            call_user_func(\NF_FU_VENDOR\Composer\Autoload\ComposerStaticInit58f069f58cffa522470ca297c1368bdf::getInitializer($loader));
        } else {
            $classMap = require __DIR__ . '/autoload_classmap.php';
            if ($classMap) {
                $loader->addClassMap($classMap);
            }
        }

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        if ($useStaticLoader) {
            $includeFiles = NF_FU_VENDOR\Composer\Autoload\ComposerStaticInit58f069f58cffa522470ca297c1368bdf::$files;
        } else {
            $includeFiles = require __DIR__ . '/autoload_files.php';
        }
        foreach ($includeFiles as $fileIdentifier => $file) {
            composerRequire58f069f58cffa522470ca297c1368bdf($fileIdentifier, $file);
        }

        return $loader;
    }
}

/**
 * @param string $fileIdentifier
 * @param string $file
 * @return void
 */
function composerRequire58f069f58cffa522470ca297c1368bdf($fileIdentifier, $file)
{
    if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
        $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

        require $file;
    }
}
