<?php

namespace NF_FU_VENDOR;

// autoload_real.php @generated by Composer
class ComposerAutoloaderInit0776a39812a2c919a0aebcbaefd09a85
{
    private static $loader;
    public static function loadClassLoader($class)
    {
        if ('NF_FU_VENDOR\\Composer\\Autoload\\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }
    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }
        require __DIR__ . '/platform_check.php';
        \spl_autoload_register(array('NF_FU_VENDOR\\ComposerAutoloaderInit0776a39812a2c919a0aebcbaefd09a85', 'loadClassLoader'), \true, \true);
        self::$loader = $loader = new \NF_FU_VENDOR\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        \spl_autoload_unregister(array('NF_FU_VENDOR\ComposerAutoloaderInit0776a39812a2c919a0aebcbaefd09a85', 'loadClassLoader'));
        require __DIR__ . '/autoload_static.php';
        \call_user_func(\NF_FU_VENDOR\Composer\Autoload\ComposerStaticInit0776a39812a2c919a0aebcbaefd09a85::getInitializer($loader));
        $loader->register(\true);
        $filesToLoad = \NF_FU_VENDOR\Composer\Autoload\ComposerStaticInit0776a39812a2c919a0aebcbaefd09a85::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = \true;
                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }
        return $loader;
    }
}
