<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'NinjaForms\\FileUploads\\' => array($baseDir . '/includes'),
    'NF_FU_VENDOR\\phpseclib\\' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'NF_FU_VENDOR\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'NF_FU_VENDOR\\Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'NF_FU_VENDOR\\Polevaultweb\\WPDropboxAPI\\' => array($vendorDir . '/polevaultweb/wp-dropbox-api/src'),
    'NF_FU_VENDOR\\Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'NF_FU_VENDOR\\JmesPath\\' => array($vendorDir . '/mtdowling/jmespath.php/src'),
    'NF_FU_VENDOR\\Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'),
    'NF_FU_VENDOR\\Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
    'NF_FU_LIB\\' => array($baseDir . '/lib'),
);
